- name: Install Software
  hosts: personalPc
  tasks:
    - name: Update all
      ansible.builtin.apt:
        upgrade: full
        update_cache: yes
    - name: Install basic software
      package:
        name: [ufw, git, flatpak, screenfetch, flameshot]
        state: present